# Nome do nosso workflow.
name: Verificador e Corretor de Qualidade

# Define o gatilho.
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Define os trabalhos (jobs).
jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Clona seu repositório.
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python.
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Passo 3: Instala as dependências.
      - name: Instalar Ruff
        run: pip install ruff

      # Passo 4: Roda o linter (isso continua sendo uma verificação importante).
      - name: Verificar código com Linter do Ruff
        run: ruff check .

      # Passo 5: Formata o código automaticamente.
      # Removemos o '--check' para que ele realmente formate os arquivos.
      - name: Formatar código com Ruff
        run: ruff format .

      # Passo 6:
      # Usa uma Action da comunidade para fazer um commit com as alterações da formatação.
      - name: Fazer commit das alterações de formatação
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit que o robô fará.
          commit_message: "style: Formata código automaticamente com Ruff ✨"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"